### ISSUE TITLE
Main Loop

### ISSUE THREAD

**Issue by mq1506** [ottoragam/Tarocco#1]
Maybe I've gone crazy but for the life of me I can't find the main loop of code in the latest commit. The Firmware and Bootloader folders seem to have identical code, maybe there was a mistake while uploading?

also, congrats on getting fully funded!

**Comment by ottoragam** [comment]
Thanks! Will upload the missing code asap

**Comment by ottoragam** [comment]
Files ready!

**Comment by mq1506** [comment]
Thanks!
