### ISSUE TITLE
Default PID values with 24v project motor

### ISSUE THREAD

**Issue by magore** [ottoragam/Tarocco#10]
Tarocco Project Manual refers to PID Resource section that does not exit.
Suggestion:  provide some initial PID values for Tarocco Crowd Supply 24V motor as a reference. 
(With firmware default values the 24v motor will start pulsing evermore strongly when encountering increased resistance - a novice might assume there is something wrong)

**Comment by ottoragam** [comment]
That part was supposed to be about PID tuning and related stuff, but I didn't had the chance to work on it (yet).
The default P value of 2500 is, in fact, with what I test the controllers after burning the firmware with the motors I sell. It probably wont perform good when the motor is coupled to a machine, but at least lets one know the system is working. I'll add some info regarding this in the manual.
Do you think the default values should be different?
