### ISSUE TITLE
contact me

### ISSUE THREAD

**Issue by bogus105** [ottoragam/Tarocco#12]
Hi, would you contact me on bogus105@wp.pl? Thanks!

**Comment by ottoragam** [comment]
Hi,
I contacted you by email a few days ago but I got no answer. Hope you can read this message.

**Comment by bogus105** [comment]
Thank you for reply. Yes now i can see your email. I'm at work in pretty remote area so i have very limited time and ability to connect to the internet:/ Got, osme questions about your servo drive. I'll try to reply your email in a minute.
