### ISSUE TITLE
Status aren't sent after some condition

### ISSUE THREAD

**Issue by zougloub** [ottoragam/Tarocco#4]
Hi,

Driving the servo with this code (python, pyserial):
```python
#!/usr/bin/env python
# Tarocco test code

import serial

port = "/dev/ttyUSB0" # eg. "COMx"
ser = serial.Serial()
ser.baudrate = 19200
ser.port = port
ser.timeout = 2.0
ser.open()
for i in range(5):
	ser.write(b"u1;")
```

It just stops sending data at the 5th iteration. I think the MCU has crashed while processing serial data, this is just one way to easily reproduce a crash.

**Comment by ottoragam** [comment]
Could you try inserting a time delay between command transmissions?

**Comment by zougloub** [comment]
Yeah, I tried to insert 10 ms / 100 ms / 200 ms sleeps between commands but it still ends up crashing after a while.
Adding a time delay shouldn't be a solution anyway, especially with a 48 MHz MCU and a 19200 b/s serial port...

**Comment by ottoragam** [comment]
Yeah, I just wanted to check if that had some effect. Let me see what else I can figure out.

**Comment by zougloub** [comment]
Took a look at the code to see if I could find something for this issue, and saw something else :)
