### ISSUE TITLE
Everything is done in the main loop

### ISSUE THREAD

**Issue by zougloub** [ottoragam/Tarocco#5]
It looks like everything is done in the `main.c` loop, quite unusual.
Usually the control loop runs as a periodic timer ISR, and the serial port management remains in low priority in the main loop.
Having the control loop running when a timer overflows ensures that the delta-t is (almost) constant.
Right now, a PID controller is running with no consideration for the time step.

**Comment by ottoragam** [comment]
Not quite. The control loop (and some other stuff) is synced to the PWM, it executes one time each cycle. It takes ~17 microseconds to run that part of the code, and the PWM period is about 10 times longer, so there shouldn't be any issue there.
