### ISSUE TITLE
Can't reset error flag + max error @ 255 is tiny

### ISSUE THREAD

**Issue by zougloub** [ottoragam/Tarocco#6]
Having a command to reset errors would be nice, errors probably happen a lot when doing PID tuning.
Also, the maximum error is not much...

**Comment by ottoragam** [comment]
I think I can add a command to reset the board via serial, thanks for the suggestion.

I'll upload a new firmware image that supports a higher maximum following error (16-bit value), probably tomorrow. I'll let you know when it is ready.

**Comment by ottoragam** [comment]
I've changed the limit for the followign error. I'm still thinking how to handle the reset feature.
